-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;
-- Database: chicken_clicker

-- DROP DATABASE IF EXISTS chicken_clicker;

CREATE DATABASE chicken_clicker
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.utf8'
    LC_CTYPE = 'en_US.utf8'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

CREATE TABLE IF NOT EXISTS public.lifehack_team_08_upgrades
(
    upgrade_id serial NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    tier integer NOT NULL,
    cost bigint NOT NULL,
    CONSTRAINT lifehack_team_08_upgrades_pkey PRIMARY KEY (upgrade_id)
    );

CREATE TABLE IF NOT EXISTS public.lifehack_team_08_users
(
    user_id serial NOT NULL,
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    eggs bigint NOT NULL DEFAULT 0,
    CONSTRAINT lifehack_team_08_users_pkey PRIMARY KEY (user_id),
    CONSTRAINT lifehack_team_08_users_username_key UNIQUE (username)
    );

CREATE TABLE IF NOT EXISTS public.lifehack_team_08_users_upgrades
(
    user_id integer NOT NULL,
    upgrade_id integer NOT NULL,
    tier integer NOT NULL,
    CONSTRAINT lifehack_team_08_users_upgrades_pkey PRIMARY KEY (user_id, upgrade_id)
    );

ALTER TABLE IF EXISTS public.lifehack_team_08_users_upgrades
    ADD CONSTRAINT lifehack_team_08_users_upgrades_upgrade_id_fkey FOREIGN KEY (upgrade_id)
    REFERENCES public.lifehack_team_08_upgrades (upgrade_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.lifehack_team_08_users_upgrades
    ADD CONSTRAINT lifehack_team_08_users_upgrades_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.lifehack_team_08_users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE CASCADE;

END;