-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.lifehack_team_1_categories DROP CONSTRAINT IF EXISTS lifehack_team_1_categories_quiz_id_fkey;

ALTER TABLE IF EXISTS public.lifehack_team_1_questions DROP CONSTRAINT IF EXISTS category_id;



DROP TABLE IF EXISTS public.lifehack_team_1_categories;

CREATE TABLE IF NOT EXISTS public.lifehack_team_1_categories
(
    id serial NOT NULL,
    category_name character varying(64) COLLATE pg_catalog."default" NOT NULL,
    quiz_id integer NOT NULL,
    CONSTRAINT lifehack_team_1_categories_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.lifehack_team_1_questions;

CREATE TABLE IF NOT EXISTS public.lifehack_team_1_questions
(
    id serial NOT NULL,
    question character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    answer character varying(256) COLLATE pg_catalog."default" NOT NULL,
    point integer NOT NULL,
    category_id integer NOT NULL,
    CONSTRAINT lifehack_team_1_questions_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.lifehack_team_1_quiz;

CREATE TABLE IF NOT EXISTS public.lifehack_team_1_quiz
(
    id serial NOT NULL,
    title character varying(256) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT lifehack_team_1_quiz_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.lifehack_team_1_categories
    ADD CONSTRAINT lifehack_team_1_categories_quiz_id_fkey FOREIGN KEY (quiz_id)
    REFERENCES public.lifehack_team_1_quiz (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.lifehack_team_1_questions
    ADD CONSTRAINT category_id FOREIGN KEY (category_id)
    REFERENCES public.lifehack_team_1_categories (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;