
-- Opret vores 5 kategorier af undskyldninger

INSERT INTO public.category (categoryname)
VALUES
    ('school'),
    ('work'),
    ('family arrangement'),
    ('funeral'),
    ('general');



-- Indsæt en masse information i tabellerne

INSERT INTO public.excuse (excusetext, sillyness_level, category)
VALUES
    -- School (category 1)
    ('My dog ate my bike, so I cannot make it to school today!', 8, 1),
    ('I got lost in the library and couldn’t find my way out.', 6, 1),
    ('A flock of birds stole my homework.', 9, 1),
    ('I accidentally time-traveled to the future and missed class.', 10, 1),
    ('My alarm clock decided to take a day off.', 4, 1),
    ('I was abducted by aliens during breakfast.', 10, 1),
    ('I got stuck in a video game and couldn’t log out.', 7, 1),
    ('My pet goldfish needed emergency surgery.', 6, 1),
    ('I thought it was Saturday.', 3, 1),
    ('My backpack ran away from home.', 8, 1),
    ('I was training my dragon and lost track of time.', 9, 1),
    ('I got into a heated debate with my reflection.', 7, 1),
    ('I was busy solving world hunger.', 5, 1),
    ('My shoes tied themselves together and I couldn’t leave.', 6, 1),
    ('I was practicing my invisibility skills and no one saw me leave.', 8, 1),
    ('I was attacked by a swarm of bees on the way to school.', 7, 1),
    ('I accidentally enrolled in a parallel universe school.', 10, 1),
    ('I was busy teaching my cat how to read.', 6, 1),
    ('I got stuck in a tree while rescuing a kite.', 7, 1),
    ('I was busy writing a novel about my life.', 5, 1),
    ('I have a doctor’s appointment.', 1, 1),
    ('I’m feeling unwell and need to rest.', 1, 1),
    ('I have a family emergency.', 1, 1),
    ('I need to study for an important exam.', 2, 1),
    ('I have a dentist appointment.', 1, 1),
    ('I’m helping my sibling with their homework.', 2, 1),
    ('I have a school project due tomorrow.', 2, 1),
    ('I’m attending a parent-teacher meeting.', 1, 1),
    ('I have a headache and need to stay home.', 1, 1),
    ('I’m participating in a school event later.', 2, 1),

    -- Work (category 2)
    ('My cat scheduled a meeting for me and forgot to tell me.', 8, 2),
    ('I was busy fighting a ninja in the parking lot.', 9, 2),
    ('My coffee cup declared a mutiny and refused to work.', 7, 2),
    ('I got stuck in a time loop and kept reliving Monday.', 10, 2),
    ('I was busy training for the office Olympics.', 6, 2),
    ('My chair decided to go on strike.', 5, 2),
    ('I was abducted by a rogue AI and held captive.', 10, 2),
    ('I accidentally joined a circus and couldn’t get out.', 9, 2),
    ('I was busy inventing a new color.', 8, 2),
    ('My keyboard started speaking in riddles.', 7, 2),
    ('I was busy negotiating peace between my plants.', 6, 2),
    ('I got lost in the break room and couldn’t find the exit.', 5, 2),
    ('I was busy teaching my goldfish how to code.', 7, 2),
    ('I was trapped in a meeting with myself.', 8, 2),
    ('I was busy building a fort out of sticky notes.', 6, 2),
    ('I accidentally became a meme and had to lay low.', 9, 2),
    ('I was busy translating my dog’s dreams.', 7, 2),
    ('I got into a staring contest with my monitor and lost.', 6, 2),
    ('I was busy inventing a new language.', 8, 2),
    ('I was busy training my desk plant to do my job.', 7, 2),
    ('I have a meeting with a client.', 1, 2),
    ('I’m working on a tight deadline.', 1, 2),
    ('I’m feeling under the weather and need to rest.', 1, 2),
    ('I have a training session I can’t miss.', 2, 2),
    ('I’m attending a conference call.', 1, 2),
    ('I need to finish a report for my boss.', 2, 2),
    ('I’m covering for a colleague who’s sick.', 2, 2),
    ('I have a performance review scheduled.', 1, 2),
    ('I’m working from home today.', 1, 2),
    ('I have a team-building activity.', 2, 2),

    -- Family Arrangement (category 3)
    ('I have to wash my hair that day.', 3, 3),
    ('My horoscope said I should avoid family gatherings this week.', 6, 3),
    ('I accidentally double-booked myself with a nap.', 5, 3),
    ('I’m busy teaching my pet rock new tricks.', 8, 3),
    ('I have to reorganize my sock drawer.', 4, 3),
    ('I’m attending a webinar on how to avoid family gatherings.', 7, 3),
    ('I’m practicing social distancing... from my family.', 6, 3),
    ('I have to babysit my neighbor’s imaginary friend.', 9, 3),
    ('I’m stuck in a never-ending game of Monopoly with myself.', 7, 3),
    ('I’m busy learning how to speak dolphin.', 8, 3),
    ('I have to finish binge-watching a show about paint drying.', 9, 3),
    ('I’m training for a marathon... in my dreams.', 7, 3),
    ('I have to help my goldfish write its memoir.', 8, 3),
    ('I’m busy building a blanket fort and can’t leave.', 6, 3),
    ('I’m attending a virtual meeting with my imaginary boss.', 7, 3),
    ('I have to alphabetize my spice rack.', 5, 3),
    ('I’m busy perfecting my pancake-flipping skills.', 6, 3),
    ('I have to attend a seminar on how to avoid awkward conversations.', 7, 3),
    ('I’m stuck in a time loop where it’s always 5 minutes before the event.', 9, 3),
    ('I’m busy counting all the grains of rice in my pantry.', 10, 3),
    ('I have to work late.', 1, 3),
    ('I’m not feeling well and need to rest.', 1, 3),
    ('I have a prior commitment I can’t reschedule.', 1, 3),
    ('I’m helping a friend move.', 2, 3),
    ('I have a doctor’s appointment.', 1, 3),
    ('I’m attending another family event.', 2, 3),
    ('I have to take care of a sick family member.', 1, 3),
    ('I’m feeling overwhelmed and need some time alone.', 2, 3),
    ('I have a work deadline I can’t miss.', 1, 3),
    ('I’m traveling and won’t be able to make it.', 1, 3),

    -- Funeral (category 4)
('I’m allergic to sadness.', 6, 4),
    ('I have a fear of coffins.', 5, 4),
    ('I’m busy attending my own emotional support group.', 7, 4),
    ('I’m afraid I’ll accidentally laugh at the wrong moment.', 8, 4),
    ('I’m allergic to funeral flowers.', 6, 4),
    ('I’m busy writing a eulogy for my sense of humor.', 9, 4),
    ('I’m scared I’ll trip and fall into the grave.', 7, 4),
    ('I’m attending a webinar on how to avoid funerals.', 8, 4),
    ('I’m busy practicing my sad face in the mirror.', 6, 4),
    ('I’m allergic to black clothing.', 5, 4),
    ('I’m afraid I’ll cry so much I’ll flood the place.', 8, 4),
    ('I’m busy organizing a funeral for my lost motivation.', 9, 4),
    ('I’m scared I’ll accidentally say, "Party in the afterlife!"', 10, 4),
    ('I’m allergic to organ music.', 7, 4),
    ('I’m busy attending a support group for funeral avoiders.', 8, 4),
    ('I’m afraid I’ll get too emotional and hug the wrong person.', 7, 4),
    ('I’m busy writing a will for my imaginary friend.', 9, 4),
    ('I’m allergic to tears.', 6, 4),
    ('I’m scared I’ll accidentally sit on the coffin.', 8, 4),
    ('I’m busy practicing my solemn nod for the next funeral.', 7, 4),
    ('I have a prior commitment I can’t reschedule.', 1, 4),
    ('I’m feeling unwell and need to rest.', 1, 4),
    ('I have to work and can’t take time off.', 1, 4),
    ('I’m attending another funeral.', 2, 4),
    ('I have a family emergency.', 1, 4),
    ('I’m not emotionally ready to attend.', 2, 4),
    ('I have a doctor’s appointment.', 1, 4),
    ('I’m traveling and won’t be able to make it.', 1, 4),
    ('I’m helping a friend with an urgent matter.', 2, 4),
    ('I have to take care of a sick family member.', 1, 4),

    -- General (category 5)
    ('I was busy chasing a rainbow to find the pot of gold.', 8, 5),
    ('I got stuck in a conversation with a street sign.', 7, 5),
    ('I was busy teaching my shadow how to dance.', 6, 5),
    ('I accidentally joined a cult of pigeons.', 9, 5),
    ('I was busy inventing a new type of cloud.', 7, 5),
    ('I got stuck in a debate with my toaster.', 8, 5),
    ('I was busy training my reflection to be more independent.', 6, 5),
    ('I accidentally became a professional sleeper.', 9, 5),
    ('I was busy inventing a new type of cheese.', 7, 5),
    ('I got stuck in a staring contest with the moon.', 8, 5),
    ('I was busy writing a love letter to my fridge.', 6, 5),
    ('I accidentally joined a secret society of lawn gnomes.', 9, 5),
    ('I was busy inventing a new type of pasta.', 7, 5),
    ('I got stuck in a conversation with a squirrel.', 8, 5),
    ('I was busy teaching my plants how to sing.', 6, 5),
    ('I accidentally became a professional cloud watcher.', 9, 5),
    ('I was busy inventing a new type of sandwich.', 7, 5),
    ('I got stuck in a debate with my reflection about life.', 8, 5),
    ('I was busy writing a symphony for my vacuum cleaner.', 6, 5),
    ('I accidentally joined a cult of sentient toasters.', 9, 5),
    ('I have a prior commitment I can’t reschedule.', 1, 5),
    ('I’m feeling unwell and need to rest.', 1, 5),
    ('I have to work late.', 1, 5),
    ('I’m attending another event.', 2, 5),
    ('I have a family emergency.', 1, 5),
    ('I’m helping a friend with something important.', 2, 5),
    ('I have a doctor’s appointment.', 1, 5),
    ('I’m traveling and won’t be able to make it.', 1, 5),
    ('I’m feeling overwhelmed and need some time alone.', 2, 5),
    ('I have a work deadline I can’t miss.', 1, 5);