@startuml
'https://plantuml.com/class-diagram

enum Species {
+Cat
+Dog
+Duck
+AsianElephant
+Chicken
}

enum Colour {
+White
+Black
+Mixed
+Brown
+Grey
}

class User{
-String: email
-String: pwd
-Profile: profile
}

class Profile{
Image: image
String: bio
String: name
int: age
Enum: Colour
Enum: Species
}

Species <|-- Profile
Colour <|-- Profile
User *-- Profile
@enduml